### PR TITLE
Fix/mailer gen rails 4.2 from #95

### PR DESCRIPTION
**Pull request by mbrand12**
[**note**]: Based on the #95

I was able to fix the problem from the above mentioned issue, `slim-rails` now properly generates mailer flies. All tests are passing and I have tested it by using the gem locally as well.

Please review the code and consider keeping a `changelog` for the project, I made one that can be used [here](https://gist.github.com/mbrand12/4c16ffd8639184e75b92), I filed my changes under "Unreleased"

I mostly had trouble with `text.slim` and considered just leaving them as `text.erb` but was able to find a workable solution (and it will not matter that much since this will always be overwritten anyway).

### CODE REVIEW

**Comment by januszm** [comment]
@mbrand12 could you rebase your changes on top of master and let us know if we still need this?

**Comment by mbrand12** [comment]
@januszm 

Pulled from upstream/master and merged, then checked out the pull request branch and rebased on top of master (no conflicts). Did a force push on my repo for the pull request branch (didn't want to push otherwise). For some reason even though the repo itself is updated it doesn't show like so on GitHub.

**Comment by mbrand12** [comment]
Everything is fine now, github just needed the time to update etc.

**Comment by januszm** [comment]
@mbrand12 but to be honest I don't understand why we'd need that change. We can't have such patches for specific Rails versions in long run. If we really need a special 'case' for Rails 4.2, I'd rather follow the convention used in this gem: https://github.com/appfolio/store_base_sti_class/tree/master/lib

**Comment by Salzig** [comment]
which is more or less a copy of https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/generators/erb/mailer/mailer_generator.rb

**Comment by mbrand12** [comment]
@Salzig , I am not really sure, its been a while since I have been using ruby, but I get the basic idea, that way every change on rails will simply be used here, and I don't really know why didn't they do that in the first place.

Either way, I wont be able to do much about it till the weekend (don't even have ruby installed currently). If somebody is interested in testing this out feel free to take over, if not I will try to inherit the erb generator and and test it out on different versions (namely some version before 4.2.0, 4.2.0 and 5.0.0).

In the mean while any other suggestions are welcome, though due to my limited ruby knowledge I don't know if I will be able to fulfill them. ^_^

**Comment by mbrand12** [comment]
@januszm  As per @Salzig suggestion I inherited the erb mailer generator run the tests and they pass. Just to be sure I also (using rwm) tested it out on two different rails versions (4.2.6 and 5.0.0rc1) and both seem to generate the mailer files properly using slim.

However for versios of rails < 4.2 this method makes the tests fail. I'll see if I can do something correct this but if not I will revert to the c005e44.

**Comment by januszm** [comment]
Try using design pattern suitable for such a case where you need to support
two different APIs
29.05.2016 5:38 PM "mbrand12" <notifications@github.com> napisał(a):

**Comment by mbrand12** [comment]
@januszm It seems that the test where failing because I forgot to properly update them, sorry newbie mistake ^_^, now they are all passing.

Just in case I installed rails 4.1.15 and tested out the generators directly and it works.

Btw @Salzig the appraisal gem really helped so thanks for that addition :)

**Comment by Salzig** [comment]
LGTM

**Comment by januszm** [comment]
👍

**Pull request merged**
