### PR TITLE
Comparable to current version of haml-rails

### PR DESCRIPTION
**Pull request by rmzr7**

### CODE REVIEW

**Comment by minad** [comment]
Could you still add at least this html2slim alias?

**Comment by januszm** [comment]
@remzr7 any chance that you could review and update your PR according to other recent changes? (rebase etc.)

**Comment by januszm** [comment]
@remzr7 please rebase and let us know if this is something we should develop further

**Comment by januszm** [comment]
Closing due to lack of activity or need for this change

**Pull request closed without merging**
