### PR TITLE
Adds compatibility for sprockets 2, 3, and 4

### LINKED ISSUE #122: Deprecation warning with Rails 4.2.7
Since updating to the 4.2.7 version of Rails, I get the following warning when launching my app:

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /home/deploy/apps/my_app/shared/bundle/ruby/2.2.0/gems/slim-rails-3.1.0/lib/slim-rails.rb:12)
```

### PR DESCRIPTION
**Pull request by cmckni3**
Fixes #122

### CODE REVIEW

**Comment by Salzig** [comment]
LGTM
@januszm ?

**Comment by januszm** [comment]
:shipit:  if tested ;)

**Comment by cmckni3** [comment]
I tried in it Rails 4. I'm pretty sure it's good in Rails 3 because of the backwards compatible changes the sprockets guide suggested.

Maybe test it on Rails 5?

**Comment by cmckni3** [comment]
Looks good on Rails 3 and Rails 5 for me

**Comment by januszm** [comment]
Looks good on Rails 5.0.0.1 . I also made  very basic test on 4.2.4 and it's OK.

**Comment by dennmart** [comment]
Checked this branch out in a Rails 5.0.0.1 app and it's working well - hopefully there's a release soon!

**Comment by januszm** [comment]
Ok, I'll merge this @Salzig please release the gem since I don't manage it @ Rubygems.

**Comment by Salzig** [comment]
Released.

**Comment by dennmart** [comment]
@januszm @Salzig Thanks so much for the prompt merge / release, it's truly appreciated :tada:

**Comment by cmckni3** [comment]
Thanks @Salzig!

**Pull request merged**
