### PR TITLE
Update gemspec to be compatible with slim 5.1

### PR DESCRIPTION
**Pull request by patrols**

### CODE REVIEW

**Comment by januszm** [comment]
Thank you! but you missed all the fun we had with the failed SLIM 5.0 release, see:
https://github.com/slim-template/slim-rails/pull/188
https://github.com/slim-template/slim-rails/issues/187

I need to close this unfortunately. Unless you want to limit the changes to slim_lint update only

**Comment by patrols** [comment]
Would it be possible to source the slim dependency to github for the master branch? The fix is already there, for the broken namespace. If not, then it would be possible to do this again once they release the next version of slim `5.0.1`.

**Comment by januszm** [comment]
@patrols I'd rather ping slim-template maintaner to release version 5.0.1 with the fix soon

**Review by januszm — APPROVED** [review]

**Comment by januszm** [comment]
Great! Thanks for the update. Did you have a chance to test this new version in production?

**Pull request merged**
