### PR TITLE
Replace Travis with Github Actions

### PR DESCRIPTION
**Pull request by davidwessman**
- Trying to switch from Travis CI to Github Actions
- Seems like tests are not running
- https://github.com/davidwessman/slim-rails/pull/1

@viktorianer it seems like the templates only work for Rails 7 :/

### CODE REVIEW

**Comment by viktorianer** [comment]
Hmpf, I think because templates are depending on helpers added in Rails 7!?

Could you please show on of errors?

And why not change linter to match Rails "defaults", instead of changing all 'strings' back to old style? 🤔

**Comment by davidwessman** [comment]
> Hmpf, I think because templates are depending on helpers added in Rails 7!?
> 
> Then we have 3 options:
> 
> * Add missing/new helpers to older Rails
> * Rewrite templates here with older helpers
> * Drop support for older Rails in Version 4+ of this gem
> 
> Could you please show on of errors?
> 
> And why not change linter to match Rails "defaults", instead of changing all 'strings' back to old style? 🤔

Some argument changed for the helpers I think :/ 
https://github.com/davidwessman/slim-rails/runs/6206810495?check_suite_focus=true#step:4:149

`ArgumentError: wrong number of arguments (given 1, expected 0)` for model_resource_name.

I just tried to get the tests to run, not sure what the Rubocop config is for slim-lint.

**Comment by viktorianer** [comment]
@januszm said before

> Thanks, this will probably be a major version bump to 4.0 since this change is not compatible with older Rails versions.

But [in changelog](https://github.com/slim-template/slim-rails/blob/master/CHANGELOG.md#340-march-2022) it reads:

> 3.4.0 (March 2022)

So, how we should fix it now?

It looks like only a call to [model_resource_name:150](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/named_base.rb#L150) is broken:

```ruby
def model_resource_name(base_name = singular_table_name, prefix: "")
```

Which was also [part of the changes](https://github.com/slim-template/slim-rails/pull/178/files):

```diff
- = form_for @<%= singular_table_name %> do |f|
+ = form_with(model: @<%= model_resource_name %>) do |form|
```

We could use `singular_table_name` here and ignore `prefix`?

**Comment by januszm** [comment]
@davidwessman  @viktorianer 

> Drop support for older Rails in Version 4+ of this gem

It looks like one of the recent changes around Rails 7 templates was released as version 3.x while, as I mentioned earlier, it was supposed to be version 4.0. 

We can fix this by removing changes  that are incompatiblewith older Rails versions, moving them to version 4.x of this gem, releasing a new 3.4.1 version without these changes (but with other useful updates), and yank version 3.4.0 (but as always, I recommend upgrading all apps to Rails 7)

**Comment by januszm** [comment]
Amazing, thank you @davidwessman .

One tiny request, could you revert the changes made for `lib/generators/...` files , `"` => `'`. Let's just use double quotes as before, change is not necessary, at some point we may introduce `.rubocop.yml`.

**Comment by davidwessman** [comment]
😊 

The test does not pass :/ so we need to have a rubocop config for that.

**Comment by davidwessman** [comment]
@januszm Can you look at #181 first? Then I can rebase this PR and fix the tests

**Comment by januszm** [comment]
@davidwessman  merged, please rebase and resolve conflicts.

**Comment by davidwessman** [comment]
Will do it first thing tomorrow 🙂

**Comment by davidwessman** [comment]
@januszm Now the tests pass on my local PR:
https://github.com/davidwessman/slim-rails/pull/1

**Comment by januszm** [comment]
@davidwessman  man your killing it! thanks 🎉

**Pull request merged**
